### ISSUE TITLE
cows' moos aren't moo-ful enough

### ISSUE THREAD

**Issue by ironon** [Fadoraaaaa/Mootiny#1]
when I spent 80 dollars on Mootiny,  I expected to achieve nirvana in the form of moos. FALSE. ADVERTISING.

admins plz fix or my dad (who owns Microsoft) will sue 🙏🙏

**Comment by adam-zhang-nvcc** [comment]
My dad (who owns Google) will also be joining the lawsuit

**Comment by Fadoraaaaa** [comment]
EXCUSE YOU that was a bargain at a DISCOUNTED PRICE!!!! Haters gonna hate. My dad (who owns Java) will be joining the lawsuit

**Comment by NoodleBirb** [comment]
Hey there, my dad (who owns apple) will also be joining the lawsuit!

**Comment by ironon** [comment]
you cannot silence us forever.

the truth always comes out eventually.

**Comment by Fadoraaaaa** [comment]
already did :)

**Comment by ironon** [comment]
[](https://tenor.com/fQApiBbXsSc.gif)

**Comment by ironon** [comment]
![image](https://github.com/user-attachments/assets/15d23b58-bf37-40fc-be98-0acb691797ef)
